// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PasswordGenerator_monodroid
{
	
	
	public partial class Resource
	{
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int password_length_array = 2131034112;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int generatedPasswordLabel = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int generatedPasswordText = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int myButton = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int passwordLengthSpinner = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int useLowercaseLetters = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int useNumbers = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int useSpecialCharacters = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int useUppercaseLetters = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int generatePassword = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int generatedPassword = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int passwordLength = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int useLowercaseLetters = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int useNumbers = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int useSpecialCharacters = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int useUppercaseLetters = 2130968578;
			
			private String()
			{
			}
		}
	}
}
